Attempt at bugfix:     Guice configuration errors:
1) No implementation for at.silverstrike.pcc.api.taskeditingpanelcontroller.TaskEditingPanelControllerFactory was bound.
  while locating at.silverstrike.pcc.api.taskeditingpanelcontroller.TaskEditingPanelControllerFactory

1 error

Caused by:

com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for at.silverstrike.pcc.api.taskeditingpanelcontroller.TaskEditingPanelControllerFactory was bound.
  while locating at.silverstrike.pcc.api.taskeditingpanelcontroller.TaskEditingPanelControllerFactory

1 error
	at com.google.inject.InjectorImpl.getProvider(InjectorImpl.java:784)
	at com.google.inject.InjectorImpl.getProvider(InjectorImpl.java:743)
	at com.google.inject.InjectorImpl.getInstance(InjectorImpl.java:793)
	at at.silverstrike.pcc.impl.centraleditingpanel.DefaultCentralEditingPanel.initTaskPanelController(DefaultCentralEditingPanel.java:223)
	at at.silverstrike.pcc.impl.centraleditingpanel.DefaultCentralEditingPanel.initGui(DefaultCentralEditingPanel.java:194)
	at at.silverstrike.pcc.impl.centraleditingpanelcontroller.DefaultCentralEditingPanelController.initGui(DefaultCentralEditingPanelController.java:101)
	at at.silverstrike.pcc.impl.centraleditingpanelcontroller.DefaultCentralEditingPanelController.initGui(DefaultCentralEditingPanelController.java:26)
	at at.silverstrike.pcc.impl.mainwindowcontroller.DefaultMainWindowController.initGui(DefaultMainWindowController.java:139)
	at at.silverstrike.pcc.ProjectControlCenterApplication.applicationInit(ProjectControlCenterApplication.java:104)
	at eu.livotov.tpt.TPTApplication.init(TPTApplication.java:68)
	at com.vaadin.Application.start(Application.java:549)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1152)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:465)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:322)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)