Bugfix: com.vaadin.event.ListenerMethod$MethodException Cause: java.lang.NoClassDefFoundError: com/google/gdata/data/extensions/BaseEventFeed      at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)      at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:162)      at com.vaadin.ui.AbstractComponent.fireEvent(AbstractComponent.java:1166)      at com.vaadin.ui.Button.fireClick(Button.java:380)      at com.vaadin.ui.Button.changeVariables(Button.java:196)      at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1297)      at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1217)      at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.doHandleUidlRequest(AbstractCommunicationManager.java:733)      at com.vaadin.terminal.gwt.server.CommunicationManager.handleUidlRequest(CommunicationManager.java:296)      at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:483)      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)      at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:362)      at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)      at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)      at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:729)      at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)      at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)      at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)      at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)      at org.mortbay.jetty.Server.handle(Server.java:320)      at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)      at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:843)      at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:647)      at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)      at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)      at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)      at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488) Caused by: java.lang.NoClassDefFoundError: com/google/gdata/data/extensions/BaseEventFeed      at java.lang.ClassLoader.defineClass1(Native Method)      at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)      at java.lang.ClassLoader.defineClass(ClassLoader.java:616)      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)      at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)      at java.net.URLClassLoader.access$000(URLClassLoader.java:58)      at java.net.URLClassLoader$1.run(URLClassLoader.java:197)      at java.security.AccessController.doPrivileged(Native Method)      at java.net.URLClassLoader.findClass(URLClassLoader.java:190)      at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:366)      at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:337)      at com.google.gdata.client.calendar.CalendarService.declareExtensions(CalendarService.java:145)      at com.google.gdata.client.calendar.CalendarService.<init>(CalendarService.java:84)      at at.silverstrike.pcc.impl.usersettingspanelcontroller.DefaultUserSettingsPanelController.exportBookingsToGoogleCalendar(DefaultUserSettingsPanelController.java:188)      at at.silverstrike.pcc.impl.usersettingspanelcontroller.DefaultUserSettingsPanelController.writeDataToGoogle(DefaultUserSettingsPanelController.java:158)      at at.silverstrike.pcc.impl.usersettingspanel.DefaultUserSettingsPanel.buttonClick(DefaultUserSettingsPanel.java:114)      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)      at java.lang.reflect.Method.invoke(Method.java:597)      at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:490)      ... 27 more Caused by: java.lang.ClassNotFoundException: com.google.gdata.data.extensions.BaseEventFeed      at java.net.URLClassLoader$1.run(URLClassLoader.java:202)      at java.security.AccessController.doPrivileged(Native Method)      at java.net.URLClassLoader.findClass(URLClassLoader.java:190)      at java.lang.ClassLoader.loadClass(ClassLoader.java:307)      at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:195)      at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:255)      at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:274)      at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader.java:214)      at java.lang.ClassLoader.loadClass(ClassLoader.java:248)      at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:375)      at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:337)      ... 48 more