Attempt at bugfix: HTTP ERROR 500
Problem accessing /pcc/. Reason:

    Guice configuration errors:

1) No implementation for at.silverstrike.pcc.api.projectnetworkdatacreator.ProjectNetworkDataCreatorFactory was bound.
  while locating at.silverstrike.pcc.api.projectnetworkdatacreator.ProjectNetworkDataCreatorFactory

1 error

Caused by:

com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for at.silverstrike.pcc.api.projectnetworkdatacreator.ProjectNetworkDataCreatorFactory was bound.
  while locating at.silverstrike.pcc.api.projectnetworkdatacreator.ProjectNetworkDataCreatorFactory

1 error
	at com.google.inject.InjectorImpl.getProvider(InjectorImpl.java:784)
	at com.google.inject.InjectorImpl.getProvider(InjectorImpl.java:743)
	at com.google.inject.InjectorImpl.getInstance(InjectorImpl.java:793)