Attempt at bugfix: HTTP ERROR 500
Problem accessing /pcc/. Reason:

    Debug ID key not found: taskeditingpanel.taskeditingpanel.4-button-dependencies

Caused by:

at.silverstrike.pcc.api.debugids.DebugIdKeyNotFoundException: Debug ID key not found: taskeditingpanel.taskeditingpanel.4-button-dependencies
	at at.silverstrike.pcc.impl.debugids.DefaultDebugIdRegistry.getDebugId(DefaultDebugIdRegistry.java:95)
	at at.silverstrike.pcc.impl.debugids.DefaultDebugIdRegistry.getDebugId(DefaultDebugIdRegistry.java:75)
	at at.silverstrike.pcc.impl.taskeditingpanel.DefaultTaskEditingPanel.createDependEditButton(DefaultTaskEditingPanel.java:198)
	at at.silverstrike.pcc.impl.taskeditingpanel.DefaultTaskEditingPanel.initGui(DefaultTaskEditingPanel.java:157)
	at at.silverstrike.pcc.impl.taskeditingpanelcontroller.DefaultTaskEditingPanelController.initGui(DefaultTaskEditingPanelController.java:79)
	at at.silverstrike.pcc.impl.taskeditingpanelcontroller.DefaultTaskEditingPanelController.initGui(DefaultTaskEditingPanelController.java:27)
	at at.silverstrike.pcc.impl.centraleditingpanel.DefaultCentralEditingPanel.initGui(DefaultCentralEditingPanel.java:205)
	at at.silverstrike.pcc.impl.centraleditingpanelcontroller.DefaultCentralEditingPanelController.initGui(DefaultCentralEditingPanelController.java:129)
	at at.silverstrike.pcc.impl.centraleditingpanelcontroller.DefaultCentralEditingPanelController.initGui(DefaultCentralEditingPanelController.java:32)
	at at.silverstrike.pcc.impl.mainwindowcontroller.DefaultMainWindowController.initGui(DefaultMainWindowController.java:138)
	at at.silverstrike.pcc.ProjectControlCenterApplication.applicationInit(ProjectControlCenterApplication.java:104)
	at eu.livotov.tpt.TPTApplication.init(TPTApplication.java:68)
	at com.vaadin.Application.start(Application.java:549)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1152)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:465)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:322)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)